### ISSUE TITLE
Broadcasting error

### ISSUE THREAD

**Issue by chkimmmmm** [xiaofanustc/ME-Sampler#4]
Hello, Xiao.

Thank you for your kind comments on issues.

Now, I faced another error.

Please, look into it and let me know if you need more inforamtion.

Thank you.

![error](https://user-images.githubusercontent.com/46791426/96405406-2ee1d800-1218-11eb-9668-dece8afd1e10.png)

**Comment by xiaofanustc** [comment]
Sorry for the error. I think it is because the version of gluoncv has been updated. For now I can't fix the error right now. I have to upgrade the version of gluoncv and update the code completely. Sorry about the inconvenience.

**Comment by chkimmmmm** [comment]
Or would you share your environment? If possible..
Thanks.

**Comment by xiaofanustc** [comment]
The code is updated and should work this time. Sorry for the inconvenience.

**Comment by chkimmmmm** [comment]
Thanks a lot. 
I will test a new version.
